spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://127.0.0.1:5430/zien
    username: zien
    password: zien2023!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    out‑of‑order: true
    baseline-on-migrate: true

path:
  reportPath: C:\srv\report\
  reportTmpPath: C:\srv\report\tmp\

rsa:
  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCqBLm44AaR7cqmByIkyxQdHPCiEPJ5eZDNKJXyPtX/QrTzM4Thx+PNVZlpgzPOs/7hnf07JA5DTojSTKEDgrQltF2z5UDufWjfk6xKjoC+7bAKe2CNRNXks9DQ89Z9k72wVZTjO66gfqh1fEpWRWjSzzxdt6uwDTA8D+cxT6wSRENgjfJ5uZfRV+MfDwM6U9sI7tPviI9kb4kXtvxNLG41HHAsDdc1EE5RTWPLFCtGzj9gBYRTHqyjBFsmjmUnXIjVWn5e78hzZg7idzTolDau7Il5sxFOyAwrqLGFn18hiIYdWzg8VFwNbgkBRToRhRdbu/QWSfFollb60ExFTI/ZAgMBAAECggEAIrVSQNajILldrGU6aC55DbRxv3QcPAZANFG7wrdnMnQowpla4EjRTYLTDcI2GlWOi/qXzrH+o2jt75irKi9NnYDjvCzqA4XgmfvoqVPMHq4hSRKE1HIgBE9dKrsMp5g4mj3uZjEx5hvVQh68gj4rNxYNachsKUWX+jr45I0yQIwPp5UXP8VSFwgvXKazAWXvPmQMHbSQEBE5GSM2MgXgsnYt6sj8twwvRMjrLg/vgXtEaN7N7XRwkb2p0923bD6cqR1gxA0Zzq9xE2aAbXruobsLUNQ/pl4eviiccnsvJSzBn18C0rhAM+XDVvPhlF8KVDwfoNldriz/yBEkksX7gQKBgQDeMlUOcE+4gKMu8bJYeuhiCPYlAmnDMeK/kEbmG3ej9+G3vxKo1eHpWRcu/GYkylgmqvlMpdreCVLuOg5a0jd5EmBWOuv/cKN7++zmMMAd9dZdYdQiWk8WcUYhB/kIiyEt+XSr4bIcQepTB5kj2j4dXL70GzE8CD+HNYlmVa060QKBgQDD4kNmGKwF2Gb42pqwN+Q8s3J257/qDeboSlXnhU2kNmaWp3BU9yFDGicXOc+6uY/fan7p0E/rLw1f9ayePiT8oeSYM/m5Ih3eckmPTBg2j2EylQ6MyItOxkemVzJQYY5h6l7JF4wENRlgRwdUMAhWBw3q218mxqNZq+MPujA2iQKBgQCANTyc2zM0u4ztDmsg4LJrts4IZs8N4R/79sziA2FSTDqCoo6qutbipRRaeSqa+eJJVYgJsP2L9odSjE8yGnAFvRO3TcJUnvLGHIQCAokoAGzTbxpPRBq0UWHst0P7qQPZGkI210DFS0dg51Z2uHv0x0orYfFTuVKmur5wPOl6sQKBgCa68BSZwDmPphyCLJ+3DVurJ3C3NczzXrqDKCUUyFs1nmcfSCikjGEWJLCE77u9wOKtzdYxJ/waW4yjqLPJGcsRv38Ql8mxIzK+aij5JLh09QTpT+0qIdE7hyMujnYyM9LMYl1kWHzketX8dUiCDsPjtS7AnTmvgNDUGZscdzfxAoGBALlX2cpn94AvECWJWG1JoIcNfYdoezmdLHpgaiCm76nO0FS+vDRISTPpIXp+tCEnj4G+xUa8N4Qx14uf7+DseNFmiFqf9f7ChL4dykedlgjFwXTE6Dn+26UGl5bvRlGBeF0SYuZtZt3mcJFIHN4LFPX5sPVjaKspx4lhR5aCiNp4
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqgS5uOAGke3KpgciJMsUHRzwohDyeXmQzSiV8j7V/0K08zOE4cfjzVWZaYMzzrP+4Z39OyQOQ06I0kyhA4K0JbRds+VA7n1o35OsSo6Avu2wCntgjUTV5LPQ0PPWfZO9sFWU4zuuoH6odXxKVkVo0s88XbersA0wPA/nMU+sEkRDYI3yebmX0VfjHw8DOlPbCO7T74iPZG+JF7b8TSxuNRxwLA3XNRBOUU1jyxQrRs4/YAWEUx6sowRbJo5lJ1yI1Vp+Xu/Ic2YO4nc06JQ2ruyJebMRTsgMK6ixhZ9fIYiGHVs4PFRcDW4JAUU6EYUXW7v0FknxaJZW+tBMRUyP2QIDAQAB